version: '3.8'

services:
  nextjs:
    container_name: portfolio-nextjs
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./content:/app/content
    networks:
      - portfolio_network

  # If you need a development environment
  nextjs-dev:
    container_name: portfolio-nextjs-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge