FROM oven/bun:1-alpine

WORKDIR /app

# Copy package.json and bun.lock
COPY package.json bun.lock ./

RUN apk add --no-cache libc6-compat || (echo "Nameserver 8.8.8.8" > /etc/resolv.conf && apk add --no-cache libc6-compat)
RUN bun install

# Copy the rest of the application
COPY . .

# Expose the port Next.js runs on
EXPOSE 3000

# Command to run the application
CMD ["bun", "run", "dev"]
