FROM node:20-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json* ./

# Install dependencies
RUN apk add --no-cache libc6-compat || (echo "Nameserver 8.8.8.8" > /etc/resolv.conf && apk add --no-cache libc6-compat)
RUN npm i

# Copy the rest of the application
COPY . .

# Expose the port Next.js runs on
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "dev"]